; Copyright (C) 2019 Georg Ziegler
;
; Permission is hereby granted, free of charge, to any person obtaining a copy of
; this software and associated documentation files (the "Software"), to deal in
; the Software without restriction, including without limitation the rights to
; use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
; of the Software, and to permit persons to whom the Software is furnished to do
; so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in
; all copies or substantial portions of the Software.
; -----------------------------------------------------------------------------
;   File: SubroutineLauncher.inc
;   Author(s): Georg Ziegler
;   Description: Include this file to access all subroutines
;

; Header guard
.ifndef SUBROUTINELAUNCHER_INC
SUBROUTINELAUNCHER_INC = 1

;-------------------------------------------------------------------------------
;   Routines found in this file
;-------------------------------------------------------------------------------
.import     SubroutineLauncher  ; Print a string at a given address
;-------------------------------------------------------------------------------

.endif  ; SUBROUTINELAUNCHER_INC
